name: Lint and analyse files

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
    phpcs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use php 7.2
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.2
                  tools: composer:v2
            - name: Validate composer.json and composer.lock
              run: composer validate
            - name: Cache module
              uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/
                  key: composer-cache
            - name: Install wdes/coding-standard
              run: composer require wdes/coding-standard
            - name: Lint files
              run: ./vendor/bin/phpcs

    php-cs-fixer:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use php 7.4
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  tools: composer:v2
            - name: Cache module
              uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/
                  key: composer-cache
            - name: Install PHP CS Fixer
              run: composer require --dev friendsofphp/php-cs-fixer
            - name: Lint files
              run: ./vendor/bin/php-cs-fixer fix --diff --dry-run -v

    phpstan:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use php 7.1
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.1
                  tools: composer:v2
            - name: Cache module
              uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/
                  key: composer-cache
            - name: Install phpstan
              run: composer require phpstan/phpstan
            - name: Analyse files
              run: ./vendor/bin/phpstan --memory-limit=1G

    doctum:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: lint php documentation
              uses: sudo-bot/action-doctum@dev
              with:
                  config-file: scripts/doctum.php
                  method: "parse"
                  cli-args: "--output-format=github --no-ansi --no-progress -v --ignore-parse-errors"
